version: 2
jobs:
    run_tests_torch:
        working_directory: ~/parsing
        docker:
            - image: circleci/python:3.7
        environment:
            OMP_NUM_THREADS: 1
        resource_class: medium
        parallelism: 1
        steps:
            - checkout
            - run: sudo pip install .[sklearn,torch,testing]
            - run: sudo pip install codecov pytest-cov
            - run: python -m pytest -n 8 --dist=loadfile -s -v ./tests/ --cov
            - run: codecov
    check_code_quality:
        working_directory: ~/parsing
        docker:
            - image: circleci/python:3.6
        resource_class: medium
        parallelism: 1
        steps:
            - checkout
            # we need a version of isort with https://github.com/timothycrosley/isort/pull/1000
            - run: sudo pip install git+git://github.com/timothycrosley/isort.git@e63ae06ec7d70b06df9e528357650281a3d3ec22#egg=isort
            - run: sudo pip install .[torch,quality]
            - run: black --check --line-length 119 --target-version py35 tests src examples utils
            - run: isort --check-only --recursive tests src examples utils
            - run: flake8 tests src examples utils
workflows:
    version: 2
    build_and_test:
        jobs:
            - check_code_quality
            - run_tests_torch